### PROXY

@proxyUrl = https://localhost:443

### Get OPTIONS
OPTIONS {{proxyUrl}}/api/v1

### Get VERSION
GET {{proxyUrl}}/api/v1/version

### Request token from TSA
# @name getTSAToken
GET {{proxyUrl}}/api/v1/token

@authToken = {{getTSAToken.response.body.*}}

### Request local token
# @name getLocalToken
GET {{proxyUrl}}/api/v1/token?local

@authToken = {{getLocalToken.response.body.*}}

### Request data

### Without token
GET {{proxyUrl}}/api/v1/providers
### With bad token
GET {{proxyUrl}}/api/v1/providers
X-Auth-Token: badtoken
### With correct token

###
# @name getProviders
GET {{proxyUrl}}/api/v1/providers
X-Auth-Token: {{authToken}}

@provider1 = {{getProviders.response.body.providers[0].name}}
###
GET {{proxyUrl}}/api/v1/providers/{{provider1}}
X-Auth-Token: {{authToken}}

###
# @name getClients
GET {{proxyUrl}}/api/v1/clients
X-Auth-Token: {{authToken}}

@client1 = {{getClients.response.body.providers[0].data.clients[0].name}}
@client1 = lis9-sipd60.11667.1448.ecs.hp.com
###
GET {{proxyUrl}}/api/v1/clients/{{client1}}
X-Auth-Token: {{authToken}}
###
GET {{proxyUrl}}/api/v1/clients/{{client1}}/history
X-Auth-Token: {{authToken}}
###
GET {{proxyUrl}}/api/v1/clients/{{client1}}/configuration
X-Auth-Token: {{authToken}}

### TOKEN SERVICE
POST https://pln-cd1-apigw-vip.ft1core.mcloud.entsvcs.net:35357/v3/auth/tokens?nocatalog
Content-Type: application/json
Accept: application/json

{
    "auth": {
        "identity": {
            "methods": [
                "password"
            ],
            "password": {
                "user": {
                    "domain": {
                        "name": "VPC_Consumer"
                    },
                    "name": "ngp_bur_user",
                    "password": "tadrur!9-iV_!55I2lFr"
                }
            }
        },
        "scope":{
            "project": { "name":"VPC_BUR4U_API",
                     "domain":{"name":"VPC_Services"}
             }
       }
    }
}
